

title: Bram Tunggala
logo: bram_pic.png
description: Data scientist and machine learning engineer with a passion for generating value using data, focusing on intuition and practical benefits. Experienced in converting financial data and operational data into actionable items. Skills include analytical thinking, creative problem-solving, data manipulation, ability to think big and create actionable first steps. Able to view from customer perspective along with management views, to enhance customer service creating a mutually beneficial relationship.
show_downloads: false
google_analytics: UA-144199159-1
theme: jekyll-theme-minimal
