

title: Bram Tunggala
logo: bram_pic.png
description: Data scientist and machine learning engineer with a passion in generating value using data, solving problems in a sensible way that suits current conditions and practical benefits. Experienced in creating data pipelines, converting data into actionable items. Skills include analytical thinking, creative problem-solving, data manipulation, ability to think big and create actionable first steps. 
show_downloads: false
google_analytics: UA-144199159-1
theme: jekyll-theme-minimal
